name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create output variables
        id: vars
        run: |
          echo "app_name=$(echo '${{ github.event.ref }}' | cut -d'-' -f1)" >> $GITHUB_OUTPUT
          echo "app_version=$(echo '${{ github.event.ref }}' | cut -d'-' -f2)" >> $GITHUB_OUTPUT

      - name: Download artifacts
        run: "bash scripts/${{ vars.app_name }}.sh ${{ vars.app_version }}"
        
      - name: Generate sha256sums
        run: "bash scripts/generate-sha256.sh dist/"

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/*"