name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Populate envs
        run: |
          echo "APP_NAME=$(echo '${{ github.ref_name }}' | cut -d'-' -f1)" >> "$GITHUB_ENV"
          echo "APP_VERSION=$(echo '${{ github.ref_name }}' | cut -d'-' -f2)" >> "$GITHUB_ENV"

      - name: Download artifacts
        run: "bash scripts/${{ env.APP_NAME }}.sh ${{ env.APP_VERSION }}"
        
      - name: Generate sha256sums
        run: "bash scripts/generate-sha256.sh dist/"

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/*"